import React, { useState, useRef, useEffect } from 'react';
import './AIAssistantModule.css';

const MOCK_RESPONSES = {
  "Which components are in high demand?": "Based on the sample lab usage data, Arduino Uno, ESP32 Development Board, and Jumper Wires show higher demand. This is a demo prediction based on sample data.",
  "Which components have low availability?": "ESP32 Development Board currently has relatively lower availability compared with its total quantity.",
  "Predict demand for Arduino": "Demo prediction: Arduino Uno → High Demand. This prediction is based on sample request and usage patterns and is not generated by a real ML model.",
  "Show popular components": "Popular components in this demo are Arduino Uno, ESP32 Development Board, Servo Motor, and DC Motor."
};

const DEFAULT_RESPONSE = "This is a prototype AI Assistant. For the current demo, I can answer questions about component demand and availability.";

const INITIAL_MESSAGES = [
  {
    id: 1,
    sender: 'bot',
    text: "Hi! I'm the Lab Hub AI Assistant. I can help you explore component availability and sample demand predictions."
  }
];

const SUGGESTED_QUESTIONS = [
  "Which components are in high demand?",
  "Which components have low availability?",
  "Predict demand for Arduino",
  "Show popular components"
];

const AIAssistantModule = () => {
  const [messages, setMessages] = useState(INITIAL_MESSAGES);
  const [inputText, setInputText] = useState('');
  const [isTyping, setIsTyping] = useState(false);
  const messagesEndRef = useRef(null);

  const scrollToBottom = () => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
  };

  useEffect(() => {
    scrollToBottom();
  }, [messages, isTyping]);

  const handleSend = (text) => {
    if (!text.trim()) return;

    const userMsg = {
      id: Date.now(),
      sender: 'user',
      text: text.trim()
    };
    
    setMessages(prev => [...prev, userMsg]);
    setInputText('');
    setIsTyping(true);

    // Simulate AI response delay
    setTimeout(() => {
      let botText = DEFAULT_RESPONSE;
      
      // Match predefined responses
      for (const [q, r] of Object.entries(MOCK_RESPONSES)) {
        if (text.toLowerCase().includes(q.toLowerCase())) {
          botText = r;
          break;
        }
      }

      const botMsg = {
        id: Date.now() + 1,
        sender: 'bot',
        text: botText
      };

      setIsTyping(false);
      setMessages(prev => [...prev, botMsg]);
    }, 1200); // 1.2s delay for realism
  };

  const handleKeyPress = (e) => {
    if (e.key === 'Enter') {
      handleSend(inputText);
    }
  };

  return (
    <div className="ai-assistant-module">
      <header className="module-header">
        <div>
          <h1 className="module-title">AI Assistant</h1>
          <p className="module-subtitle">Ask about component availability and demand.</p>
        </div>
      </header>

      <div className="chat-container">
        <div className="chat-header">
          <div className="bot-avatar-header">
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <rect x="3" y="11" width="18" height="10" rx="2"></rect>
              <circle cx="12" cy="5" r="2"></circle>
              <path d="M12 7v4"></path>
              <line x1="8" y1="16" x2="8" y2="16"></line>
              <line x1="16" y1="16" x2="16" y2="16"></line>
            </svg>
          </div>
          <div className="chat-header-info">
            <h2>AI Assistant</h2>
            <span className="demo-status">Demo Assistant</span>
          </div>
        </div>

        <div className="chat-messages">
          {messages.map(msg => (
            <div key={msg.id} className={`chat-bubble-wrapper ${msg.sender === 'user' ? 'user-wrapper' : 'bot-wrapper'}`}>
              {msg.sender === 'bot' && (
                <div className="bot-avatar">🤖</div>
              )}
              <div className={`chat-bubble ${msg.sender === 'user' ? 'user-bubble' : 'bot-bubble'}`}>
                {msg.text}
              </div>
            </div>
          ))}
          
          {isTyping && (
            <div className="chat-bubble-wrapper bot-wrapper">
              <div className="bot-avatar">🤖</div>
              <div className="chat-bubble bot-bubble typing-indicator">
                <span>.</span><span>.</span><span>.</span>
              </div>
            </div>
          )}
          <div ref={messagesEndRef} />
        </div>

        {/* Suggested Questions (only show if few messages to keep it clean) */}
        {messages.length < 5 && (
          <div className="suggested-questions">
            {SUGGESTED_QUESTIONS.map((q, idx) => (
              <button 
                key={idx} 
                className="suggested-btn"
                onClick={() => handleSend(q)}
                disabled={isTyping}
              >
                {q}
              </button>
            ))}
          </div>
        )}

        <div className="chat-input-area">
          <input
            type="text"
            className="chat-input"
            placeholder="Type your question..."
            value={inputText}
            onChange={(e) => setInputText(e.target.value)}
            onKeyPress={handleKeyPress}
            disabled={isTyping}
          />
          <button 
            className="chat-send-btn"
            onClick={() => handleSend(inputText)}
            disabled={!inputText.trim() || isTyping}
          >
            <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
              <line x1="22" y1="2" x2="11" y2="13"></line>
              <polygon points="22 2 15 22 11 13 2 9 22 2"></polygon>
            </svg>
          </button>
        </div>
      </div>
    </div>
  );
};

export default AIAssistantModule;
